"""añadir descripcion a gastos

Revision ID: eb76f04759c3
Revises: 412a92341086
Create Date: 2026-10-05 10:38:35.826038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb76f04759c3'
down_revision: Union[str, Sequence[str], None] = '412a92341086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos', 'descripcion')
    # ### end Alembic commands ###
